- pom.xml
- spark-connector-oceanbase-common/pom.xml
- spark-connector-oceanbase/pom.xml
- spark-connector-oceanbase/spark-connector-oceanbase-2.4/pom.xml
- spark-connector-oceanbase/spark-connector-oceanbase-3.1/pom.xml
- spark-connector-oceanbase/spark-connector-oceanbase-3.2/pom.xml
- spark-connector-oceanbase/spark-connector-oceanbase-3.3/pom.xml
- spark-connector-oceanbase/spark-connector-oceanbase-3.4/pom.xml
- spark-connector-oceanbase/spark-connector-oceanbase-base/pom.xml
> hotfix: fix revision and other warnings in pom

- .github/workflows/push_pr.yml
- README.md
- README_CN.md
- docs/spark-connector-obkv-hbase.md
- docs/spark-connector-obkv-hbase_cn.md
- pom.xml
- spark-connector-obkv-hbase/pom.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-2.4/pom.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-2.4/src/main/resources/oceanbase-table-client/log/log4j/log-conf.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-3.1/pom.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-3.1/src/main/resources/oceanbase-table-client/log/log4j/log-conf.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-3.2/pom.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-3.2/src/main/resources/oceanbase-table-client/log/log4j/log-conf.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-3.3/pom.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-3.4/pom.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/pom.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/src/main/java/com/oceanbase/spark/config/OBKVHbaseConfig.java
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/src/main/java/com/oceanbase/spark/obkv/HTableClientUtils.java
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/src/main/scala/com/oceanbase/spark/HBaseRelation.scala
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/src/main/scala/com/oceanbase/spark/OBKVHBaseSparkSource.scala
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/src/test/resources/log4j2-test.properties
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/src/test/resources/sql/htable.sql
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/src/test/scala/com/oceanbase/spark/OBKVHBaseConnectorITCase.scala
- spark-connector-oceanbase-e2e-tests/pom.xml
- spark-connector-oceanbase-e2e-tests/src/test/resources/sql/htable.sql
- spark-connector-oceanbase-e2e-tests/src/test/scala/com/oceanbase/spark/OBKVHBaseE2eITCase.scala
Add obkv-hbase module.
- About obkv-hbase e2e tests
- Since the docker images of spark 3.2 and above are no longer built on the java8 platform, only Spark 3.1 and 2.4 versions were tested.
- obkv-hbase-client-java issue: https://github.com/oceanbase/obkv-hbase-client-java/issues/128
> feat: Add obkv-hbase module.

- pom.xml
Update the pom.xml file to prepare for release.
> Enhancement: Update the pom.xml file to prepare for release.

- spark-connector-oceanbase-common/src/main/java/com/oceanbase/spark/config/Config.java
- spark-connector-oceanbase-common/src/main/java/com/oceanbase/spark/config/ConfigConstants.java
- spark-connector-oceanbase/spark-connector-oceanbase-3.1/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcReader.scala
- spark-connector-oceanbase/spark-connector-oceanbase-3.1/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcScanBuilder.scala
- spark-connector-oceanbase/spark-connector-oceanbase-3.1/src/main/scala/com/oceanbase/spark/writer/v2/DirectLoadWriteBuilderV2.scala
- spark-connector-oceanbase/spark-connector-oceanbase-3.1/src/main/scala/com/oceanbase/spark/writer/v2/JDBCWriteBuilder.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/catalog/OceanBaseCatalog.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/catalog/OceanBaseTable.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseMySQLDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseOracleDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/OBMySQLLimitPartition.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcReader.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcScanBuilder.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBMySQLPartition.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/utils/OBJdbcUtils.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/utils/OceanBaseConnectionProvider.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/writer/DirectLoadWriteBuilder.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/writer/DirectLoadWriter.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/writer/v2/DirectLoadWriteBuilderV2.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/writer/v2/DirectLoadWriteV2.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/writer/v2/JDBCWriteBuilder.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/writer/v2/JDBCWriter.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/org/apache/spark/sql/ExprUtils.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/org/apache/spark/sql/OceanBaseSparkDataSource.scala
> Enhancement: Refactor the configuration system in the catalog implementation.

- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseMySQLDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcReader.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBMySQLPartition.scala
> Enhancement: Add new configuration options.

- docs/spark-connector-obkv-hbase.md
- docs/spark-connector-obkv-hbase_cn.md
Fix bugs in docs of obkv-hbase.
> hotfix: Fix bugs in docs of obkv-hbase.

- README.md
- README_CN.md
- docs/spark-catalog-oceanbase.md
- docs/spark-catalog-oceanbase_cn.md
> Doc: Add doc for catalog.

- spark-connector-oceanbase/spark-connector-oceanbase-3.1/src/main/scala/com/oceanbase/spark/catalog/OceanBaseTable.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/catalog/OceanBaseCatalog.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/catalog/OceanBaseTable.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/writer/v2/DirectLoadWriteBuilderV2.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/writer/v2/JDBCWriteBuilder.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
> Enhancement: Support table truncate and overwrite.

- docs/spark-catalog-oceanbase.md
- docs/spark-catalog-oceanbase_cn.md
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/utils/OceanBaseConnectionProvider.scala
> BugFix: Fix JDBC driver register

- docs/spark-catalog-oceanbase.md
- docs/spark-catalog-oceanbase_cn.md
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/directload/DirectLoadUtils.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OceanBaseMySQLConnectorITCase.scala
Add direct-load.username configuration option to be compatible with OceanBase on the cloud.
> Enhancement: Add direct-load.username configuration option to be compatible with OceanBase on the cloud.

- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/catalog/OceanBaseTable.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/utils/OBJdbcUtils.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
> feat: Supports table delete

- spark-connector-oceanbase-e2e-tests/src/test/scala/com/oceanbase/spark/OceanBaseCatalogE2eITCase.scala
Add direct-load test to catalog's e2e test.
> Enhancement: Add direct-load test to catalog's e2e test.

- spark-connector-oceanbase/spark-connector-oceanbase-3.1/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcScanBuilder.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/catalog/OceanBaseTable.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseMySQLDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcReader.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcScanBuilder.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBMySQLPartition.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/utils/OBJdbcUtils.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/resources/sql/mysql/products.sql
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
Refactor partition logic to optimize spark query performance.
> Enhancement: Refactor partition logic to optimize spark query performance.

- docs/spark-catalog-oceanbase.md
- docs/spark-catalog-oceanbase_cn.md
- spark-connector-oceanbase-common/src/main/java/com/oceanbase/spark/config/ConfigConstants.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/catalog/OceanBaseCatalog.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseMySQLDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcReader.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/utils/OBJdbcUtils.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
Fix row size too large issue when create table.
> Enhancement: Fix row size too large issue when create table.

- .github/workflows/push_pr.yml
- docs/spark-catalog-oceanbase.md
- docs/spark-catalog-oceanbase_cn.md
- spark-connector-obkv-hbase/pom.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-3.5/pom.xml
- spark-connector-oceanbase-e2e-tests/pom.xml
- spark-connector-oceanbase/pom.xml
- spark-connector-oceanbase/spark-connector-oceanbase-3.5/pom.xml
- spark-connector-oceanbase/spark-connector-oceanbase-base/pom.xml
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/org/apache/spark/sql/reader/JDBCLimitRDD.scala
> Enhancement: Supports Spark 3.5 version

- docs/spark-catalog-oceanbase.md
- docs/spark-catalog-oceanbase_cn.md
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/catalog/OceanBaseCatalog.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
> Enhancement: Allow enable-always-nullable during schema inference.

- docs/spark-catalog-oceanbase.md
- docs/spark-catalog-oceanbase_cn.md
Modify the description of the document
close #47
fix doc
> [Doc]:Modify the parameter name in the document

- docs/spark-catalog-oceanbase.md
- docs/spark-catalog-oceanbase_cn.md
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseMySQLDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBMySQLPartition.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/utils/OceanBaseConnectionProvider.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
> Enhancement: Support creating primary key table.

- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBMySQLPartition.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
Refine partition logic of int primary key table.
> Enhancement: Refine partition logic of int primary key table.

- spark-connector-oceanbase/pom.xml
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/writer/v2/DirectLoadWriteV2.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OceanBaseMySQLConnectorITCase.scala
Bump version of obkv-table-client to 2.0
> Enhancement: bump version of obkv-table-client to 2.0

- docs/spark-catalog-oceanbase.md
- docs/spark-catalog-oceanbase_cn.md
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcReader.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBMySQLPartition.scala
> Enhancement: Supports setting query_timeout hint.

- pom.xml
> release v1.2

- pom.xml
> prepare v1.3

- spark-connector-obkv-hbase/pom.xml
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/src/main/scala/com/oceanbase/spark/HBaseRelation.scala
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/src/test/resources/sql/htable.sql
- spark-connector-obkv-hbase/spark-connector-obkv-hbase-base/src/test/scala/com/oceanbase/spark/OBKVHBaseConnectorITCase.scala
feat: obkv-hbase supports writing multiple CF
> feat: obkv-hbase supports writing multiple CF

- README.md
- README_CN.md
- docs/spark-catalog-oceanbase.md
- docs/spark-catalog-oceanbase_cn.md
- pom.xml
> Enhancement: Refine doc

- docs/spark-catalog-oceanbase.md
- docs/spark-catalog-oceanbase_cn.md
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseMySQLDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseOracleDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/writer/v2/JDBCWriter.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/resources/sql/mysql/products.sql
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OceanBaseMySQLConnectorITCase.scala
> Enhancement: Non-primary key tables with unique_index support upsert writing.

- spark-connector-oceanbase/spark-connector-oceanbase-3.2/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcScanBuilder.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseMySQLDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/dialect/OceanBaseOracleDialect.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcReader.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/reader/v2/OBJdbcScanBuilder.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/scala/com/oceanbase/spark/utils/OBJdbcUtils.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
> feat: Supports aggregate pushdown

- .gitignore
- pom.xml
- spark-connector-oceanbase/spark-connector-oceanbase-2.4/src/main/java/com/oceanbase/spark/config/OceanBaseConfig.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/config/OceanBaseUserInfo.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/main/java/com/oceanbase/spark/directload/DirectLoadUtils.java
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OBCatalogMySQLITCase.scala
- spark-connector-oceanbase/spark-connector-oceanbase-base/src/test/scala/com/oceanbase/spark/OceanBaseMySQLConnectorITCase.scala
> BugFix: fix failed to direct-load on ob-cloud
